services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DB_HOST=db
      - DB_USERNAME=vscode
      - DB_PASSWORD=password
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: vscode
      POSTGRES_DB: ruby_on_rails_devcontainer_development
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
